#!/usr/bin/env python3

import csv
import pprint
from pathlib import Path


INPUT_FILE = Path(__file__).with_name("opus.csv")
OUTPUT_FILE = Path(__file__).with_name("opus_prepared.py")


def power_score(power_factor: str) -> int:
    """
    Converts the block symbols into a numeric score.
    Example: '█ █ █' becomes 3.
    """
    if not power_factor:
        return 0

    return power_factor.count("█")


def prepare_opus():
    if not INPUT_FILE.exists():
        raise FileNotFoundError(f"Could not find {INPUT_FILE}")

    opus_lookup = {}

    with INPUT_FILE.open("r", encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)

        for row in reader:
            snp = row["SNP"].strip()

            if not snp:
                continue

            opus_lookup[snp] = {
                "gene": row["Gene"].strip(),
                "snp": snp,
                "snp_label": row["SNP Label"].strip(),
                "risk": row["Risk"].strip(),
                "type": row["Type"].strip(),
                "power_factor": row["Power Factor"].strip(),
                "power_score": power_score(row["Power Factor"]),
            }

    with OUTPUT_FILE.open("w", encoding="utf-8") as file:
        file.write("# Auto-generated by prepare_opus.py\n")
        file.write("# Do not edit this file manually.\n\n")
        file.write("OPUS_LOOKUP = ")
        file.write(pprint.pformat(opus_lookup, width=120, sort_dicts=True))
        file.write("\n")

    print(f"Prepared {len(opus_lookup):,} OPUS records")
    print(f"Output written to {OUTPUT_FILE}")


if __name__ == "__main__":
    prepare_opus()
